### ISSUE TITLE
Unable to Start Calibration using sh2_startCal()

### ISSUE THREAD

**Issue by lewispg228** [hcrest/sh2#11]
Hi There,
We are trying to use the function [sh2_startCal()](https://github.com/ceva-dsp/sh2/blob/main/sh2.c#L2526), but in our use-case/code it doesn't seem to complete. Would you mind taking a look? We are currently working on an example to calibrate the sensor, which lives on [this branch](https://github.com/sparkfun/SparkFun_BNO08x_Arduino_Library/blob/Calibration_example/examples/Example_19_Calibrate/Example_19_Calibrate.ino) of our Arduino Library.

Our example calls our function [calibrateALL()](https://github.com/sparkfun/SparkFun_BNO08x_Arduino_Library/blob/Calibration_example/src/SparkFun_BNO08x_Arduino_Library.cpp#L970), which calls both `sh2_setCalConfig()` (which seems to complete) and then `sh2_startCal()` (which then stops our program from continuing).

![image](https://github.com/ceva-dsp/sh2/assets/601236/036dc307-c20b-4081-a8b3-a1c854ebd0c0)

Here is a print out from our terminal verifying the stop point:

![image](https://github.com/ceva-dsp/sh2/assets/601236/929e4987-19b5-4bf7-8d2b-89fafc6cbe1a)

Also, does the argument `interval_us` need to be within a specific range? And does this affect/play-into the report intervals set later in our example when we enable the sensor outputs? We have tried many different "reasonable" values here (i.e. 1000uS, 10000uS), but it still seems to get stuck.

Any insights would be much appreciated,
Thanks in advance,
Pete

**Comment by kay-ceva** [comment]
Hi Pete,

[sh2_startCal()](https://github.com/ceva-dsp/sh2/blob/main/sh2.c#L2526) is for __simple calibration_ feature and this is not available for the BNO08X. This is an advanced feature to calibrate statically (not dynamically) and only available in the newer platform (FSP200 and FSP201). 

So, you won't be able to get any return from the BNO08X.

I guess you meant the dynamic calibration for the BNO08X. sh2_setCalConfig() will enable the dynamic calibration. By default, BNO086 enables SH2_CAL_ACCEL|SH2_CAL_MAG and that is all you need. You do not need to enable explicitly.
Please refer to the BNO08X datasheet Section 3.

SH2_CAL_ACCEL - accelerometer calibration in 3D
SH2_CAL_GYRO - gyroscope calibration for "hand-held" devices (can't be placed on the table)
SH2_CAL_MAG - magnetometer calibration
SH2_CAL_PLANAR - accelerometer calibration in planar (108 deg turn) for ground roving robot application
SH2_CAL_ON_TABLE - more accurate gyroscope calibration on table based, can't be disabled and always enabled.

Hope this helps.

**Comment by lewispg228** [comment]
Hi @kay-ceva ,
Thank you for this info. It is indeed helpful. We have modified our example to focus on the control of the dynamic calibration (that is, choosing which sensor you'd like calibration to be active/inactive).

We are still interested in the interactive calibration abilities of the BNO086. In the datasheet, it states to look at "reference 0", but we have not been able to find this link.

![image](https://github.com/ceva-dsp/sh2/assets/601236/9853d762-0b93-4c96-8a2c-9c0f38ab58b1)

Do you have any more info about this?

Let us know and thanks again,
Pete

**Comment by lewispg228** [comment]
Thank you for this info and app note. We will include it in our hookup guide for any advanced users that want to do this sort of calibration.

Thanks!
-Pete

**Comment by kay-ceva** [comment]
@lewispg228,

We decided to hide this document in public and requires NDA in place to share. So please hold on sharing this document in your hookup guide. I need to check with my team. Thank you for your understanding.

**Comment by lewispg228** [comment]
@kay-ceva , Okay, we will wait to hear from you about sharing on our hookup guide. 

Also, if you'd like to prevent sharing this to the public without NDA, you may want to consider deleting your comment above with the link. 

Thank again!

**Comment by kay-ceva** [comment]
@lewispg228, we will update the BNO08X datasheet to remove the reference 0. Sorry about the confusion.

**Comment by LNqueen** [comment]
how about use sh2_setCalConfig() to calibration the bno080 chip? Is this calibration process consistent with the above?

**Comment by LNqueen** [comment]
![image](https://github.com/ceva-dsp/sh2/assets/30171606/68d6d303-9c7f-453a-8b02-b2a1ed8c87c4)
In addition, I would like to ask what is the special orientation in the calibration process?

**Comment by kay-ceva** [comment]
@LNqueen,
[If you are asking](https://github.com/ceva-dsp/sh2/issues/11#issuecomment-1834653266), yes, the BNO080 chip is the same. The default calibration flag is set to SH2_CAL_ACCEL|SH2_CAL_MAG for protocols except UART-RVC (only SH2_CAL_PLANAR). SH2_CAL_ON_TABLE is set always and can't be disabled.
For the orientation, you can think the device in a cube and place your device in 4 to 6 faces stationary to calibrate the accelerometer in 3D option (SH2_CAL_ACCEL).

**Comment by LNqueen** [comment]
thanks a lot!

**Comment by LNqueen** [comment]
by the way, can I use sh2_getCalConfig() to get the current calibration status? For example, the calibration value of a certain axis?

**Comment by kay-ceva** [comment]
You can use sh2_getCalConfig() to get the flags of dynamic calibration configuration settings. 
// Flags for sensors field of sh_calConfig
#define SH2_CAL_ACCEL (0x01)
#define SH2_CAL_GYRO  (0x02)
#define SH2_CAL_MAG   (0x04)
#define SH2_CAL_PLANAR (0x08)
#define SH2_CAL_ON_TABLE (0x10)

Not sure about your question, "the calibration value of a certain axis". You can get the calibration status from the calibrated sensor report. For example, accelerometer (report ID 0x01) has a field "status" to indicate the calibration level (but not per axis).

**Comment by LNqueen** [comment]
If I do this,First of all, I started using sh2_setCalConfig(SH2_ACCELEROMETER) to calibrate the acceleration. Then I stayed in each cube position for 1 second (maybe for 2 to 3 seconds), and next I use sh2_saveDcdNow() to save the calibrated values so that the calibrated data can be used the next time I power on,  can I normally calibrate the accelerometer?
