### ISSUE TITLE
"sh2_getOscType" returns nothing

### ISSUE THREAD

**Issue by FIRSTDRAGONX88** [hcrest/sh2#2]
the following function in the file sh2.c returns nothing:

int sh2_getOscType(sh2_OscType_t *pOscType)
{
    sh2_t *pSh2 = &_sh2;

    return opProcess(pSh2, &getOscTypeOp);
}

it has to look like this:

int sh2_getOscType(sh2_OscType_t *pOscType)
{
	sh2_t *pSh2 = &_sh2;

	pSh2->opData.getOscType.pOscType = pOscType;

	return opProcess(pSh2, &getOscTypeOp);
}

**Comment by dave20874** [comment]
Thanks for the heads-up.  I’ll work on updating the public repository.

Dave
